### ISSUE TITLE
return api.php

### ISSUE THREAD

**Issue by airasz** [nosignals/esp-network-monitor#1]
lagi nyobain om pake esp32 . uri masih defaut. gak ada data. dicoba akses apinya via browser malah return api.php bukan json data. kenapa ya?

**Comment by nosignals** [comment]
updah pasang php di openwrtnya kah?
kalo udah edit file file di openwrtnya /etc/config/uhttpd
di bagian `config uhttpd 'main'` tambahin config dibawah
```
	option interpreter '.php=/usr/bin/php-cgi'
	list index_page 'index.php'
```
contoh
```
config uhttpd 'main'
	list listen_http '0.0.0.0:80'
	list listen_http '[::]:80'
	list listen_https '0.0.0.0:443'
	list listen_https '[::]:443'
	option redirect_https '0'
	option home '/www'
	option rfc1918_filter '1'
	option max_connections '100'
	option cert '/etc/uhttpd.crt'
	option key '/etc/uhttpd.key'
	option cgi_prefix '/cgi-bin'
	list lua_prefix '/cgi-bin/luci=/usr/lib/lua/luci/sgi/uhttpd.lua'
	option network_timeout '30'
	option http_keepalive '20'
	option tcp_keepalive '1'
	option ubus_prefix '/ubus'
	option script_timeout '3600'
	option interpreter '.php=/usr/bin/php-cgi'
	list index_page 'index.php'
	option max_requests '50'

```

**Comment by airasz** [comment]
php7? udah. okeh. dicoba perintah selanjutnya

**Comment by airasz** [comment]
sekarang returnnya: "Unable to launch the requested CGI program:
  /usr.bin.php-cgi: No such file or directory". php7-cgi udah terinstall

**Comment by nosignals** [comment]
`opkg install php7 php7-cgi php7-cli php7-mod-ctype php7-mod-curl php7-mod-fileinfo php7-mod-gettext php7-mod-gmp php7-mod-iconv php7-mod-json php7-mod-pcntl php7-mod-session`
install package itu coba
